// <auto-generated />
using EFCore_practice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_practice.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260728163551_add-relationships")]
    partial class addrelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_practice.Models.Department", b =>
                {
                    b.Property<int>("departmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentID"));

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentNumber")
                        .HasColumnType("int");

                    b.HasKey("departmentID");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EFCore_practice.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<double>("location")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("EFCore_practice.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<double>("age")
                        .HasColumnType("float");

                    b.Property<int>("departmentID")
                        .HasColumnType("int");

                    b.Property<double>("grade")
                        .HasColumnType("float");

                    b.Property<int>("hotelID")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("departmentID");

                    b.HasIndex("hotelID")
                        .IsUnique();

                    b.ToTable("students");
                });

            modelBuilder.Entity("EFCore_practice.Models.Student", b =>
                {
                    b.HasOne("EFCore_practice.Models.Department", "D")
                        .WithMany("students")
                        .HasForeignKey("departmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_practice.Models.Hotel", "h")
                        .WithOne("s")
                        .HasForeignKey("EFCore_practice.Models.Student", "hotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("D");

                    b.Navigation("h");
                });

            modelBuilder.Entity("EFCore_practice.Models.Department", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("EFCore_practice.Models.Hotel", b =>
                {
                    b.Navigation("s")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
